[2025-08-17T01:18:28.223+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-17T01:18:28.248+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: churn_pipeline_dag.feature_store manual__2025-08-17T01:18:13.230301+00:00 [queued]>
[2025-08-17T01:18:28.254+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: churn_pipeline_dag.feature_store manual__2025-08-17T01:18:13.230301+00:00 [queued]>
[2025-08-17T01:18:28.255+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-17T01:18:28.269+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): feature_store> on 2025-08-17 01:18:13.230301+00:00
[2025-08-17T01:18:28.280+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=99) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-17T01:18:28.282+0000] {standard_task_runner.py:64} INFO - Started process 101 to run task
[2025-08-17T01:18:28.282+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'churn_pipeline_dag', 'feature_store', 'manual__2025-08-17T01:18:13.230301+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/churn_pipeline_dag.py', '--cfg-path', '/tmp/tmp0rk3kh1z']
[2025-08-17T01:18:28.284+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask feature_store
[2025-08-17T01:18:28.334+0000] {task_command.py:426} INFO - Running <TaskInstance: churn_pipeline_dag.feature_store manual__2025-08-17T01:18:13.230301+00:00 [running]> on host 625cbff09405
[2025-08-17T01:18:28.429+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='churn_pipeline_dag' AIRFLOW_CTX_TASK_ID='feature_store' AIRFLOW_CTX_EXECUTION_DATE='2025-08-17T01:18:13.230301+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-17T01:18:13.230301+00:00'
[2025-08-17T01:18:28.431+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-17T01:18:28.491+0000] {logging_mixin.py:188} INFO - ERRORS: python: can't open file '/opt/***/dags/../02_Source_Code/step7_feature_store/feature_store.py': [Errno 2] No such file or directory
[2025-08-17T01:18:28.492+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-17T01:18:28.493+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-17T01:18:28.506+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=churn_pipeline_dag, task_id=feature_store, run_id=manual__2025-08-17T01:18:13.230301+00:00, execution_date=20250817T011813, start_date=20250817T011828, end_date=20250817T011828
[2025-08-17T01:18:28.538+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-08-17T01:18:28.560+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-17T01:18:28.563+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
